version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-teste
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "martins"
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: "test_db"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
