"""Initial migration3

Revision ID: a8d19b9f1821
Revises: 1e39e6b0dbc3
Create Date: 2025-02-21 01:02:05.452667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d19b9f1821'
down_revision: Union[str, None] = '1e39e6b0dbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('id_group', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('active_user', sa.String(length=1), nullable=False),
    sa.Column('user_comments', sa.String(length=90), nullable=True),
    sa.PrimaryKeyConstraint('id_group')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_group')
    # ### end Alembic commands ###
