"""Initial migration5

Revision ID: ef322bacc83f
Revises: d7fea598f3b1
Create Date: 2025-02-21 01:09:41.782500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef322bacc83f'
down_revision: Union[str, None] = 'd7fea598f3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group', 'user_comments',
               existing_type=mysql.VARCHAR(length=90),
               type_=sa.String(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group', 'user_comments',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=90),
               existing_nullable=True)
    # ### end Alembic commands ###
