"""Initial migration2

Revision ID: fc995217c140
Revises: ef6bb8f7e144
Create Date: 2025-02-21 00:47:33.846814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc995217c140'
down_revision: Union[str, None] = 'ef6bb8f7e144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id_group', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(50), nullable=False),
    sa.Column('active_user', sa.String(1), nullable=False),
    sa.Column('user_comments', sa.String(90), nullable=True),
    sa.PrimaryKeyConstraint('id_group')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_groups')
    # ### end Alembic commands ###
